### 4.1.5 불리언 색인
- 중복된 이름이 포함된 배열이 있다고 하자. 
- 그리고 numpy.random모듈에 있는 randn함수를 사용해서 임의의 표준정규분포 데이터를 생성하자. 

In [2]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [3]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [4]:
data

array([[ 1.61540953, -1.10738388,  0.57469659,  1.53195615],
       [ 0.68540979,  0.05133838,  0.50694833,  1.33587381],
       [-0.67343062,  2.65727435, -0.62022009,  0.85993488],
       [-2.11250686, -1.54822656,  0.38704072,  0.14243503],
       [-0.00779475,  0.79781774, -1.61017037, -0.87123609],
       [ 0.68314378,  0.48235408,  0.03470771,  1.09812879],
       [-1.35017173, -0.24635787,  1.84274679,  0.25477797]])

- 각각의 이름은 data배열의 각 로우에 대응한다고 가정하자. 
- 만약에 전체 로우에서 'Bob'과 같은 이름을 선택하려면 산술연산과 마찬가지로 배열에 대한 비교연산(== 같은)도 벡터화된다.
- 따라서 names를 'Bob'문자열과 비교하면 불리언 배열을 반환한다. 

In [5]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [6]:
data[names == 'Bob']

array([[ 1.61540953, -1.10738388,  0.57469659,  1.53195615],
       [-2.11250686, -1.54822656,  0.38704072,  0.14243503]])

- 이 불리언 배열은 배열의 색인으로 사용할 수 있다. 
- 이 불리언 배열은 반드시 색인하려는 축의 길이와 동일한 길이를 가져야 한다. 
- 불리언 배열 색인도 슬라이스 또는 숫자와 함께 혼용할 수 있다.

In [8]:
data[names == 'Bob', 2:]

array([[0.57469659, 1.53195615],
       [0.38704072, 0.14243503]])

In [9]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [14]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [15]:
data[mask]

array([[ 1.61540953, -1.10738388,  0.57469659,  1.53195615],
       [-0.67343062,  2.65727435, -0.62022009,  0.85993488],
       [-2.11250686, -1.54822656,  0.38704072,  0.14243503],
       [-0.00779475,  0.79781774, -1.61017037, -0.87123609]])

- 배열에 불리언 색인을 이용해서 데이터를 선택하면 반환되는 배열의 내용이 바뀌지 않더라도 항상 데이터 복사가 이루어진다. 
- 불리언 배열에 값을 대입하는 것은 상식선에서 이루어지며, data에 저장된 모든 음수를 0으로 대입하려면 아래와 같이 하면 된다. 

In [16]:
data[data < 0] = 0

In [17]:
data

array([[1.61540953, 0.        , 0.57469659, 1.53195615],
       [0.68540979, 0.05133838, 0.50694833, 1.33587381],
       [0.        , 2.65727435, 0.        , 0.85993488],
       [0.        , 0.        , 0.38704072, 0.14243503],
       [0.        , 0.79781774, 0.        , 0.        ],
       [0.68314378, 0.48235408, 0.03470771, 1.09812879],
       [0.        , 0.        , 1.84274679, 0.25477797]])

In [21]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.68540979, 0.05133838, 0.50694833, 1.33587381],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.68314378, 0.48235408, 0.03470771, 1.09812879],
       [0.        , 0.        , 1.84274679, 0.25477797]])

### 4.1.6 팬시색인
- 팬시색인은 정수배열을 사용한 색인을 설명하기 위해 NumPy에서 차용한 단어다. 
- 8 X 4 크기의 배열이 있다고 하자

In [24]:
arr = np.empty((8,4))
arr

array([[2.23198518e-314, 2.23250583e-314, 2.23784458e-314,
        2.23784386e-314],
       [2.23323866e-314, 2.23341854e-314, 2.23727828e-314,
        2.26776346e-314],
       [2.26776349e-314, 2.26776098e-314, 2.23341857e-314,
        2.23784471e-314],
       [2.23341860e-314, 2.23784477e-314, 2.26776352e-314,
        2.23784483e-314],
       [2.26776505e-314, 2.26776507e-314, 2.26776355e-314,
        2.23784622e-314],
       [2.23784518e-314, 2.26776358e-314, 2.23341874e-314,
        2.23482197e-314],
       [2.24240509e-314, 2.23172368e-314, 2.23266060e-314,
        2.26776361e-314],
       [2.26776510e-314, 2.26664894e-314, 2.26776513e-314,
        2.26776365e-314]])

In [26]:
arr1 = np.empty([8,4])
arr1 == arr

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [27]:
for i in range(8):
    arr[i] = i
    
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

- 특정한 순서로 로우를 선택하고 싶다면 그냥 원하는 순서가 명시된 정수가 담긴 ndarray나 리스트를 넘기면 된다. 

In [28]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [29]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

- 다차원 색인 배열을 넘기는 것은 조금 다르게 동작하며, 각각의 색인 튜플에 대응하는 1차원 배열이 선택된다. 

In [31]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

- 이 예제를 잠시 살펴보자. 결과를 보면 (1,0), (5,3), (7,1), (2,2)에 대응하는 요소가 선택되었다. 
- 이 예제에서 팬시 색인은 우리의 예상과는 조금 다르게 동작했다. 
- 행렬의 행과 열에 대응하는 사각형 모양의 값이 선택되기를 기대했는데 사실 그렇게 하려면 다음처럼 선택 해야 한다. 

In [36]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

- np.ix_ 함수를 사용하면 같은 결과를 얻을 수 있는데, 1차원 정수 배열 2개를 사각형 영역에서 사용할 색인으로 반환해준다. 

### 4.1.7 배열 전치와 축 바꾸기
- 배열 전치는 데이터를 복사하지 않고 데이터 모양이 바뀐 뷰를 반환하는 특별한 기능이다. 
- ndarray는 transpose메서드와 T라는 이름의 특수한 속성을 가지고 있다. 

In [37]:
arr = np.arange(15).reshape((3, 5))

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [40]:
arr = np.random.randn(6, 3)

- 행렬 계산을 할 때 자주 사용하게 될 텐데, 예를 들면 행령의 내적 XTX는 np.dot를 이용해서 구할 수 있다. 

In [41]:
arr = np.random.randn(6, 3)
np.dot(arr.T, arr)

array([[11.90419135,  2.58176786,  1.31259649],
       [ 2.58176786,  7.16996609, -4.81086459],
       [ 1.31259649, -4.81086459,  7.37480946]])

- 다차원 배열의 경우 transpose메서드는 튜플로 축 번호를 받아서 치환한다. 
- 실제로 계산하면 머리에 쥐가 날지도 모른다. 

In [42]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [43]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

- .T속성을 이용하여 간단한 전치는 축을 뒤바꾸는 특별한 경우다. 
- ndarray에는 swapaxes메서드가 있는데 2개의 축 번호를 받아서 배열을 뒤바꾼다. 

In [44]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [46]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])