## Numpy 기본: 배열과 벡터 계산

Numerical Python의 줄임말인 Numpy는 고성능의 과학계산 컴퓨팅과 데이터 분석에 필요한 기본 패키지다. 
NumPy는 이 책에서 사용하는 거의 모든 종류의 고수준 도그를 작성하는데 토대가 되는 패키지로 NumPy에서 제공하는 기능은 다음과 같다. 

- 빠르고 메모리를 효율적으로 사용하여 벡터 산술연산과 세련된 브로드캐스팅 기능을 제공하는 다차원 배열인 ndarray
- 반복문을 작성할 필요 없이 전체 데이터 배열에 대해 빠른 연산을 제공하는 표준 수학 함수
- 선형대수, 난수 발생기, 푸리에 변환 기능
- C, C++, 포트란으로 쓰여진 코드를 통합하는 도구

마지막 항목은 생태계 관점에서 봤을 때 가장 중요한 기능으로, NumPy는 사용하기 편한 C API를 제공하며 데이터를 다른 저수준 언어로 쓰여진 외부 라이브러리에 쉽게 전달할 수 있다. 또한 외부 라이브러리에서 반환된 데이터를 파이썬의 NumPy배열 형태로 불러올 수도 있다. 이 기능은 파이썬을 레거시 C/C++/포트란 기반을 감싸서 동적이며 쉽게 사용할 수 있는 인터페이스를 만들 수 있는 언어로 만들어 준다. 

NumPy 그 자체로는 고수준의 데이터 분석 기능을 제공하지 않으므로 먼저 NumPy배열과 배열 기반의 컴퓨팅에 대한 이해를 한다면 Pandas같은 도구를 좀 더 효율적으로 사용할 수 있다. 만약 파이썬을 처음 접하고 직접 pandas를 이용해서 데이터를 다루고 싶다면 이 장은 건너 뛰어도 좋다. 브로드캐스팅 같은 NumPy의 고급 기능은 12장을 참고하자. 

대부분의 데이터 분석 애플리케이션에서 중요하게 사용되는 기능은 다음과 같다.

- 벡터 배열상에서 데이터 개조, 정제, 부분 집합, 필터링, 변형, 다른 종류 연산의 빠른 수행
- 정렬, 유일 원소 찾기, 집합연산 같은 일반적인 배열 처리 알고리즘
- 통계의 효과적인 표현과 데이터의 수집/요약
- 다른 종류의 데이터 묶음을 병합하고 엮기 위한 데이터 정렬과 데이터 간의 관계 조작
- if-elif-else를 포함하는 반복문 대신 사용할 수 있는 조건절을 표현할 수 있는 배열 표현
- 데이터 그룹 전체에 적용할 수 있는 수집, 변형, 함수 적용 같은 데이터 처리. 

NumPy는 이런 연산을 위한 기본 라이브러리를 제공하므로 대부분의 데이터 분석(특히 구조화된 데이터나 표 형식의 데이터)은 일반적인 작업을 단순하고 간단하게 만들어주는 풍부하면서도 고수준인 인터페이스를 제공하는 pandas와 함께 사용한다. 또한 Pandas는 NumPy에는 없는 시계열 같은 다양한 도메인 특화 기능을 제공한다. 

In [1]:
import numpy as np

### 4.1 NumPy ndarray: 다차원 배열 객체

In [2]:
data = np.random.randn(2, 3)
data

array([[-0.33023968, -1.21261404,  1.33964237],
       [ 0.80496806,  0.2072137 ,  1.25398873]])

In [3]:
data * 10

array([[ -3.30239679, -12.12614039,  13.39642368],
       [  8.04968064,   2.07213704,  12.53988727]])

In [4]:
data + data

array([[-0.66047936, -2.42522808,  2.67928474],
       [ 1.60993613,  0.41442741,  2.50797745]])

In [5]:
data.shape

(2, 3)

In [6]:
data.dtype

dtype('float64')

### 4.1.1 ndarray 생성

- array함수를 이용 array(순차적인 객체)

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
arr2.ndim

2

In [14]:
arr2.shape

(2, 4)

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.empty((2, 3, 2))

array([[[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 7.46301161e-038],
        [1.28822975e-231, 1.28822975e-231]]])

In [20]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 4.1.2 ndarray의 자료형

- 자료형, dtype은 ndarray가 특정 데이터를 메모리에서 해석하기 위해 필요한 정보를 담고 있는 특수한 객체다. 
- dtype이 있기에 NumPy가 강력하면서도 유연한 도구가 될 수 있었는데, 대부분의 데이터는 디스크에서 데이터를 읽고 쓰기 편하도록 하위 레벨의 표현에 직접적으로 맞춰져 있으며 C나 포트란 같은 저수준 언어로 작성된 코드와 쉽게 연동이 가능하다. 
- 산술 데이터의 dtype은 float, int같은 자료형의 이름과 하나의 원소가 차지하는 비트 수로 이루어진다. 
- 파이썬의 float객체에서 사용되는 표준 배정밀도 부동소수점 값은 8바이트 혹은 64비트로 이루어지는데, 이 자료형은 NumPy에서 float64로 표현된다. 

In [21]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)
arr1. dtype

dtype('float64')

In [22]:
arr2.dtype

dtype('int32')

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

- ndarray의 astype메서드를 사용해서 배열의 dtype을 다른 형으로 명시적 변경이 가능하다. 

In [24]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [28]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [30]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 4.1.3 배열과 스칼라 간의 연산
- 배열은 for 반복문을 작성하지 않고 데이터를 일괄처리할 수 있기 때문에 중요하다. 이를 벡터화라고하는데, 같은 크기의 배열간 산술연산은 배열의 각 요소 단위로 적용된다. 
- 스칼라 값에 대한 산술연산은 각 요소로 전달된다. 

### 크기가 다른 배열 간의 연산은 브로드캐스팅이라고 하는데 12장에서 자세히 다룬다.

In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [35]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### 4.1.4 색인과 슬라이싱 기초
- NumPy배열 색인에 대해서는 다룰 주제가 많다. 
- 데이터의 부분집합이나 개별 요소를 선택하기 위한 수많은 방법이 존재한다. 
- 1차원 배열은 단순하며 표면적으로는 파이썬의 리스트와 유사하게 동작한다. 

In [36]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
arr[5]

5

In [38]:
arr[5:8]

array([5, 6, 7])

In [40]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

- 브로드캐스팅 : arr[5:8] = 12 처럼 배열 조각에 스칼라 값을 대입하면 12가 선택 영역 전체로 전파된다.
- 리스트와의 중요한 차이점은 배열조각(slice)은 원본 배열의 뷰(View)라는 점이다. 
- 즉, 데이터는 복사되지 않고 뷰에 대한 변경은 그대로 원본 배열에 반영된다는 것이다. 

In [41]:
arr_slice = arr[5:8]
arr_slice[1] = 12345

In [42]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [43]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

### Numpy를 처음 접했거나 특히 데이터 복사가 자주 일어나는 다른 배열 프로그래밍 언어를 사용해본 적이 있다면 데이터가 복사되지 않는다는 점에 당황할 것이다. 
- Numpy는 대용량 데이터 처리를 염두에 두고 설계되었기 때문에 만약 NumPy가 데이터 복사를 남발한다면 성능과 메모리 문제에 직면하게 될 것이다. 
- 만약에 뷰 대신 ndarray슬라이스의 복사본을 얻고 싶다면 arr[5:8].copy()를 사용해서 명시적으로 배열을 복사하면 된다. 
- 다차원 배열을 다루려면 좀 더 많은 옵션이 필요하다. 2차원 배열에서 각 색인에 해당하는 요소는 스칼라 값이 아니라 1차원 배열이 된다. 

In [45]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr2d[2]

array([7, 8, 9])

- 다차원 배열을 다루려면 좀 더 많은 옵션이 필요하다. 2차원 배열에서 각 색인에 해당하는 요소는 스칼라 값이 아니라 1차원 배열이 된다. 
- 따라서 개별 요소는 재귀적으로 접근해야 한다. 
- 하지만 그렇게 하기는 귀찮으나 콤마로 구분된 색인 리스트를 넘기면 된다. 
- 따라서 다음의 두 표현은 같다. 

In [46]:
arr2d[0][2]

3

In [47]:
arr2d[0, 2]

3

- 다차원 배열에서 마지막 색인을 생략하면 반환되는 객체는 상위 차원의 데이터를 포함하고 있는 한 차원 낮은 ndarray가 된다. 
- arr3d가 2 X 2 X 3 크기의 배열이라면 arr3d[0]은 2 X 3크기의 배열이다. 

In [56]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [57]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [58]:
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d[0] = old_values

In [60]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [61]:
arr3d[1, 0]

array([7, 8, 9])

- 이런 식으로 arr3d[1, 0]은 (1, 0)으로 색인되는 1차원 배열 형태인 모든 값을 반환한다. 
- 여기서 살펴본 선택된 배열의 부분집합은 모두 배열의 뷰를 반환한다는 점을 기억하자. 

### 슬라이스 색인
- 파이썬의 리스트와 같은 1차원 객체처럼 ndarray는 익숙한 문법으로 슬라이싱할 수 있다. 

In [62]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

- 다차원 객체는 숫자를 조합해서 하나 이상의 축을 기준으로 슬라이싱할 수 있다.
- 앞에서 살펴본 arr2d를 생각해보자. 이 배열을 슬라이싱 하는 방법은 조금 다르다. 

In [63]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

- 확인했듯이 첫 번째 축인 0번 축을 기준으로 슬라이싱되었다. 
- 슬라이스는 축을 따라 선택 영역내의 요소가 선택된다. 
- 색인을 여러 개 넘겨서 다차원을 슬라이싱하는 것도 가능하다. 

In [65]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

- 이렇게 슬라이싱하면 항상 같은 차원의 배열에 대한 뷰를 얻게 된다. 
- 정수 색인과 슬라이스를 함께 사용하면 한 차원 낮은 슬라이스를 얻을 수 있다. 

In [67]:
arr2d[1, :2]

array([4, 5])

In [68]:
arr2d[2, :1]

array([7])

- 그냥 콜론만 쓰면 전체 축을 선택한다는 의미이므로 이렇게 하면 원래 차원의 슬라이스를 얻을 수 있다. 

In [69]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [70]:
arr2d[:2, 1:] = 0

In [72]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])