## 4.5 선형대수
- 행렬의 곱셈, 분할, 행렬식, 정사각 행렬 수학같은 선형대수는 배열을 다루는 라이브러리에서 중요한 부분이다.
- MATLAB같은 다른 언어와 달리 2개의 2차원 배열을 *연산자로 곱하는 건 행렬 곱셈이 아니라 대응하는 각각의 원소의 곱을 계산하는 것이다.
- 행렬 곱셈은 배열 메서드이자 numpy네임스페이스 안에 있는 함수인 dot함수를 사용해서 계산한다.

In [3]:
import numpy as np

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

In [6]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [7]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [8]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

- numpy.linalg는 행렬의 분할과 역행렬, 행렬식 같은 것을 포함하고 있다. 
- 이는 MATLAB, R 같은 언어에서 사용하는 표준 포트란 라이브러리인 BLAS, LAPACK또는 Intel MKL(NumPy빌드에 따라 따르다)를 사용해서 구현되었다.

In [9]:
from numpy.linalg import inv, qr

X = np.random.randn(5, 5)
mat = X.T.dot(X)

inv(mat)

array([[ 253.31608365,  180.04614051, -139.43323817, -230.16798051,
         205.96252701],
       [ 180.04614051,  128.41619778,  -99.03357947, -163.73171353,
         146.46389233],
       [-139.43323817,  -99.03357947,   77.05042499,  126.82696813,
        -113.21033561],
       [-230.16798051, -163.73171353,  126.82696813,  209.46580163,
        -187.182059  ],
       [ 205.96252701,  146.46389233, -113.21033561, -187.182059  ,
         167.93423766]])

In [10]:
mat.dot(inv(mat))

array([[ 1.00000000e+00,  9.53412099e-15,  1.50070273e-13,
         1.58922143e-14,  1.15977378e-13],
       [-3.68603694e-14,  1.00000000e+00,  6.79948830e-14,
         5.19160216e-15, -6.65791361e-14],
       [ 3.53319461e-14,  4.82799748e-15,  1.00000000e+00,
         8.46815605e-14, -4.89378993e-14],
       [ 7.76099301e-14,  7.42873718e-16, -1.52354658e-14,
         1.00000000e+00, -9.65296671e-15],
       [-1.52430192e-13, -8.91577816e-14, -4.50759881e-14,
         5.57722664e-14,  1.00000000e+00]])

In [11]:
q, r = qr(mat)

In [12]:
r

array([[-7.00853437e+00,  2.69565970e+00, -6.61335175e+00,
         2.02425347e+00,  4.04471313e+00],
       [ 0.00000000e+00, -3.50747232e+00,  3.64405030e+00,
        -5.34761057e+00, -4.43723943e-01],
       [ 0.00000000e+00,  0.00000000e+00, -4.29187469e+00,
         3.98378590e+00,  1.54783045e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -1.54549169e+00, -1.72728616e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  2.67330140e-03]])

### 자주 사용하는 numpy.linalg함수 (선형대수 함수)
- numpy.diag   
- numpy.dot : 행렬 곱셈
- numpy.trace : 행렬의 대각선 원소의 합을 계산한다.
- numpy.linalg.det : 행렬식을 계산한다.
- numpy.linalg.eig : 정사각 행렬의 고유 값과 고유벡터를 계산한다.
- numpy.linalg.inv : 정사각 행렬의 역행렬을 계산한다.
- numpy.linalg.pinv : 행렬의 무어 - 펜로즈 유사역원 역행렬을 구한다.
- numpy.linalg.qr : QR분해를 계산한다.
- numpy.linalg.svd : 특이값 분해(SVD)를 계산한다.
- numpy.linalg.solve : A가 정사각 행렬일 때, Ax = b를 만족하는 x를 구한다.
- numpy.linalg.lstsq : y = xb를 만족하는 최소제곱해를 구한다.

### 4.6 난수 생성
- numpy.random모듈을 파이썬 내장 random함수를 보강하여 다양한 종류의 확률분포로부터 효과적으로 표본 값을 생성하는 데 주로 사용된다.
- 예를 들어 normal을 사용하여 표준정규분포로 부터 4 X 4 크기의 표본을 생성할 수 있다.

In [13]:
samples = np.random.normal(size = (4, 4))
samples

array([[-0.41757917, -1.38914849,  0.09145937,  0.62221   ],
       [-1.08288709, -2.58639398,  0.0748852 ,  0.60021911],
       [ 0.84762365, -2.27486826, -0.02673312,  0.19126108],
       [ 0.22476035, -1.12990125,  0.46612382,  0.98977   ]])

- 이에 비해 파이썬 내장 random모듈은 한 번에 하나의 값만 생성할 수 있다.
- 아래 성능 비교에서 알 수 있듯이 numpy.random은 매우 큰 표본을 생성하는데 생성하는데 파이썬 내장 모듈보다 수십 배 이상 빠르다. 

In [14]:
from random import normalvariate
N = 1000000
%timeit samples = [normalvariate(0, 1) for _ in range(N)]

556 ms ± 9.83 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [15]:
%timeit np.random.normal(size=N)

23.3 ms ± 658 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


### 난수 생성 함수 (numpy.random함수)
- seed : 난수 발생기의 시드를 지정한다.
- permutation : 순서를 임의로 바꾸거나 임의의 순열을 반환한다.
- shuffle : 리스트나 배열의 순서를 뒤섞는다.
- rand : 균등분포에서 표본을 추출한다.
- randint : 주어진 최소/최대 범위 안에서 임의의 난수를 추출한다.
- randn : 표준편차가 1이고 평균값이 0인 정규분포에서 표본을 추출한다.
- binomial : 이항분포에서 표본을 추출한다.
- normal : 정규분포(가우시안)에서 표본을 추출한다.
- beta : 베타분포에서 표본을 추출한다.
- chisquare : 카이제곱분포에서 표본을 추출한다.
- gamma : 감마분포에서 표본을 추출한다.
- uniform : 균등(0,1)분포에서 표본을 추출한다.