## Multivariate Linear Regression

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [8]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):
    def __init__(self):
        self.x_data = [[73, 80, 75],
                      [93, 88, 93],
                      [89, 91, 90],
                      [96, 98, 100],
                      [73, 66, 70]]
        self.y_data = [[152],[185],[180],[196],[142]]
        
    def __len__(self):
        return len(self.x_data)
    
    def __getitem__(self, idx):
        x = torch.FloatTensor(self.x_data[idx])
        y = torch.FloatTensor(self.y_data[idx])
        
        return x, y

In [10]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [ ]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
    for batch_idx, samples in enumerate(dataloader):
        x_train, y_train = samples
        # H(x)계산
        prediction = model(x_train)
        
        # cost계산
        cost = F.mse_loss(prediction, y_train)
        
        # cost로 H(x)계산
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
    print("Epoch {:4d}/{} Batch {}/{} Cost:{:.6f}".format(epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()))

In [6]:
# getitem에서는 인덱스 하나를 받아서 그에 맞는 입력과 출력 데이터를 찾은 후 이 입출력 데이터를 torch.tensor형태로 반환
# dataloader를 이용가능 

In [11]:
# enumerate(dataloader)
# - minibatch인덱스와 데이터를 받음. 

In [12]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [14]:
W = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)
hypothesis = x_train*W + b
cost = torch.mean((hypothesis - y_train)**2)

In [15]:
optimizer = optim.SGD([W, b], lr= 0.01)

optimizer.zero_grad()
cost.backward()
optimizer.step()

In [33]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

optimizer = optim.SGD([W, b], lr = 0.01)

nb_epochs = 100
for epoch in range(1, nb_epochs + 1):
    #가설함수
    hypothesis = x_train*W + b
    
    #cost함수
    cost = torch.mean((hypothesis - y_train)**2)
    
    #W, b를 학습
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    print(W, b)
    #print(hypothesis)
    print(cost.item())

tensor([0.1867], requires_grad=True) tensor([0.0800], requires_grad=True)
18.66666603088379
tensor([0.3527], requires_grad=True) tensor([0.1509], requires_grad=True)
14.770962715148926
tensor([0.5004], requires_grad=True) tensor([0.2138], requires_grad=True)
11.691540718078613
tensor([0.6318], requires_grad=True) tensor([0.2695], requires_grad=True)
9.257344245910645
tensor([0.7487], requires_grad=True) tensor([0.3188], requires_grad=True)
7.333169460296631
tensor([0.8528], requires_grad=True) tensor([0.3625], requires_grad=True)
5.812135219573975
tensor([0.9453], requires_grad=True) tensor([0.4012], requires_grad=True)
4.6097636222839355
tensor([1.0277], requires_grad=True) tensor([0.4353], requires_grad=True)
3.65927791595459
tensor([1.1011], requires_grad=True) tensor([0.4655], requires_grad=True)
2.907895803451538
tensor([1.1663], requires_grad=True) tensor([0.4922], requires_grad=True)
2.313894510269165
tensor([1.2245], requires_grad=True) tensor([0.5157], requires_grad=True)
1.84

In [34]:
#데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])
#모델 초기화
W = torch.zeros(1)
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train + W
    
    # cost gradient 계산
    cost = torch.mean((hypothesis - y_train)**2)
    gradient = torch.sum((W * x_train - y_train) * x_train)
    
    print("Epoch {:4d}/{} W: {:.3f}, Cost: {:.6f}".format(epoch, nb_epochs, W.item(), cost.item()))
    
    W -= lr*gradient

Epoch    0/10 W: 0.000, Cost: 0.000000
Epoch    1/10 W: 1.400, Cost: 1.960000
Epoch    2/10 W: 0.840, Cost: 0.705600
Epoch    3/10 W: 1.064, Cost: 1.132096
Epoch    4/10 W: 0.974, Cost: 0.949455
Epoch    5/10 W: 1.010, Cost: 1.020585
Epoch    6/10 W: 0.996, Cost: 0.991825
Epoch    7/10 W: 1.002, Cost: 1.003280
Epoch    8/10 W: 0.999, Cost: 0.998690
Epoch    9/10 W: 1.000, Cost: 1.000525
Epoch   10/10 W: 1.000, Cost: 0.999790


In [ ]:
import torch.optim as optim

# optimizer 설정 : learning rate parameter vlftn!
optimizer = optim.SGD([W], lr=0.15)

# cost로 H(X) 개선
optimizer.zero_grad() # gradient를 0으로 초기화
cost.backward() # gradient 계산
optimizer.step() # gradient descent



In [39]:
#데이터
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

#모델 초기화
W = torch.zeros(1)

#optimizer 설정
optimizer = optim.SGD([W], lr=0.15)

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train + W
    
    # cost gradient 계산
    cost = torch.mean((hypothesis - y_train)**2)
    
    print("Epoch {:4d}/10 W: {:.3f} Cost: {:.6f}".format(epoch, W.item(), cost.item()))

Epoch    0/10 W: 0.000 Cost: 0.000000
Epoch    1/10 W: 0.000 Cost: 0.000000
Epoch    2/10 W: 0.000 Cost: 0.000000
Epoch    3/10 W: 0.000 Cost: 0.000000
Epoch    4/10 W: 0.000 Cost: 0.000000
Epoch    5/10 W: 0.000 Cost: 0.000000
Epoch    6/10 W: 0.000 Cost: 0.000000
Epoch    7/10 W: 0.000 Cost: 0.000000
Epoch    8/10 W: 0.000 Cost: 0.000000
Epoch    9/10 W: 0.000 Cost: 0.000000
Epoch   10/10 W: 0.000 Cost: 0.000000
