### Tensor

1. 1차원(스칼라)
2. 2차원(매트릭스)
3. 3차원(벡터)
4. 4차원(텐서)
5. 5차원(텐서)
6. 6차원(텐서)

### Tensor, Matrix의 크기!

- 2D Tensor(Typical Simple Setting)
    - |t| = (batch size, dim)
    - batch size X dimension ( 64 X 256 )

3D Tensor(Typical Comuper Vision)
    - |t| = (batch size, width, height)
    - batch size : 이미지의 개수
    - width X height : 이미지의 크기

3D Tensor(Typical Natural Language Processing)
    - |t| = (batch size, width, height)
    - batch size: 문장의 개수
    - width X height = 문장

In [1]:
import numpy as np
import torch

### 1D Array with NumPy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
print('Rank of t:', t.ndim) 
print('Shape of t:', t.shape)

Rank of t: 1
Shape of t: (7,)


In [5]:
print('t[0] t[1] t[-1]=', t[0], t[1], t[-1]) #Element
print('t[2:5] t[4:-1]=', t[2:5], t[4:-1]) #slicing

t[0] t[1] t[-1]= 0.0 1.0 6.0
t[2:5] t[4:-1]= [2. 3. 4.] [4. 5.]


### 2D Array with NumPy

In [8]:
t = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print('Rank of t:', t.ndim) 
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


### 3D Array with NumPy

In [10]:
t = torch.FloatTensor([0, 1, 2, 3, 4, 5])
print(t)

tensor([0., 1., 2., 3., 4., 5.])


In [12]:
print('Rank of t:', t.ndim) 
print('Shape of t:', t.shape)
print('Size of t',t.size())

Rank of t: 1
Shape of t: torch.Size([6])
Size of t torch.Size([6])


In [14]:
t = torch.FloatTensor([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [15]:
print('Rank of t:', t.ndim) 
print('Shape of t:', t.shape)
print('Size of t',t.size())

Rank of t: 2
Shape of t: torch.Size([4, 3])
Size of t torch.Size([4, 3])


### BroadCasting

In [16]:
# Same Shape
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])
print(m1 + m2)

tensor([5., 5.])


In [17]:
# Vector + Scalar
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [18]:
# Vector + Vector (Different Shape)
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([[3],[4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication

In [19]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.matmul(m2))

tensor([[ 5.],
        [11.]])


In [20]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1.mul(m2))

tensor([[1., 2.],
        [6., 8.]])


In [21]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])
print(m1 * m2)

tensor([[1., 2.],
        [6., 8.]])


### Mean

In [22]:
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [23]:
t = torch.LongTensor([1,2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [24]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [30]:
print(t.mean())
print(t.mean(dim=0))
print(t.mean(dim=1))
#print(t.mean(dim=2))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])


In [31]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


In [32]:
print(t.max())

tensor(4.)


In [33]:
print(t.max(dim=0)[0])
print(t.max)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


### View(Reshape)

In [36]:
t = np.array([[[0,1,2],
               [3,4,5]],
             
              [[6,7,8],
               [9,10,11]]])

In [38]:
ft = torch.FloatTensor(t)
ft.shape

torch.Size([2, 2, 3])

In [39]:
ft.view(-1,3)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [40]:
ft.view(-1,3).shape

torch.Size([4, 3])

In [41]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze

In [43]:
ft = torch.FloatTensor([[0],[1],[2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [45]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


### Unsqueeze

In [46]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [47]:
print(ft.unsqueeze(0)) #dim = 0, dim0에 1을 넣음
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [49]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [50]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [51]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [52]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [53]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [54]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [56]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [57]:
x = torch.FloatTensor([[1,2],[3,4]])
y = torch.FloatTensor([[5,6],[7,8]])
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [58]:
x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [59]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [60]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [61]:
x = torch.FloatTensor([[0,1,2],[2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [62]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [64]:
x = torch.FloatTensor([[1,2],[3,4]])
print(x.mul(2))
print(x)
print(x.mul_(2))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
