In [1]:
import numpy as np

In [16]:
#f : 함수, 일반적으로 람다. 
#x : numpy행렬
def numerical_derivative(f, x):
    delta_x = 1e-4
    grad = np.zeros_like(x)
    
    it = np.nditer(x, flags=['multi_index'], op_flags = ['readwrite'])
    
    while not it.finished:
        idx = it.multi_index
        
        tmp_val = x[idx]
        x[idx] = float(tmp_val) + delta_x
        fx1 = f(x)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x)
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

In [17]:
#f = x2

def func (x):
    y = x*x
    return y

In [18]:
f = lambda x : func(x)

In [72]:
x = np.array([3.0])
x

array([3.])

In [73]:
numerical_derivative(f, x)

TypeError: numerical_derivative() missing 1 required positional argument: 'y'

In [45]:
delta_x = 1e-4
grad = np.zeros_like(x)
    
it = np.nditer(x, flags=['multi_index'], op_flags = ['readwrite'])
    
while not it.finished:
    idx = it.multi_index
    print(idx)
        
    tmp_val = x[idx]
    x[idx] = float(tmp_val) + delta_x
    fx1 = f(x)
        
    x[idx] = tmp_val - delta_x
    fx2 = f(x)
    grad[idx] = (fx1 - fx2) / (2*delta_x)
        
    x[idx] = tmp_val
    it.iternext()
    
# C나 자바에서는 tmp_val을 하지 않아도 된다. (mutable type이 아니기때문에)
# 그러나 tmp_val은 편미분으로도 작용하므로 꼭 해줘야 한다. 그러므로 c나 자바도 해줘야함. 
# 자바에도 iterator
# const iterator ci = & 
# iterator, C++, point
# ci가 가리키고 있는 곳에 넣고 c1 . next()
# 현재 가지고 있는 데이터를 가리킨 다음 .next()를 이용한다. 


## 이터레이터 : 원소의 처음 부터 끝 까지


(0,)


(0,)

In [22]:
it.finished

True

In [27]:
x = np.array([3])
x

array([3])

In [28]:
grad

array([25000])

In [53]:
def func1(x):
    W = x**2
    return W

f = lambda W: func1(W)

W = np.array([3.0])

ret = numerical_derivative(f, W)

grad = np.zeros_like(W)
it = np.nditer(W, flags=['multi_index'])
idx = it.multi_index

print("degug 1. initial input variable = ", W)
print("debug 2. initial grad= ", grad)
print("===============================================")

delta_w = 1e-4
tmp_val = W[idx]
print(tmp_val)
W[idx] = float(tmp_val) + delta_w
fw1 = f(W)
print(W[idx])


W[idx] = tmp_val - delta_w
fw2 = f(W)
grad[idx] = (fw1 - fw2) / 2*delta_x

print("debug 3. idx = ", idx, "x[idx] = ", x[idx])
print("debug 4. grad[idx] = ", grad[idx])
print("debug 5. grad", grad)
print("===============================================")
print('type(ret)=', type(ret), 'ret_val=', ret)

TypeError: numerical_derivative() missing 1 required positional argument: 'y'

In [34]:
#f(x, y) = 2x + 3xy + y^3
#f'(1.0, 2.0)

In [35]:
def func3(x, y):
    return 2*x + 3*x*y + y**3

In [36]:
f = lambda x, y : func3(x, y)

In [40]:
W = np.array([1.0, 2.0])

In [57]:
#f : 함수, 일반적으로 람다. 
#x : numpy행렬
def numerical_derivative(f, x, y):
    delta_x = 1e-4
    delta_y = 1e-4
    grad_x = np.zeros_like(x)
    grad_y = np.zeros_like(y)
    
    it_x = np.nditer(x, flags=['multi_index'], op_flags = ['readwrite'])
    it_y = np.nditer(y, flags=['multi_index'], op_flags = ['readwrite'])
    
    while not it_x.finished:
        idx = it_x.multi_index
        idy = it_y.multi_index
        
        tmp_val = x[idx] # 편미분을 위해 저장
        x[idx] = float(tmp_val) + delta_x #분자 계산
        fx1 = f(x) #미분 함수 호출 해서 결과를 fx1에 저장(람다)
        
        x[idx] = tmp_val - delta_x
        fx2 = f(x) #미분 함수 호출
        grad[idx] = (fx1 - fx2) / (2*delta_x)
        
        x[idx] = tmp_val
        it.iternext()
        
    return grad

array([0, 0, 0])

In [61]:
a = np.arange(6)

In [64]:
for x in a.nditer(x, flags = []:
    print(x)

0
1
2
3
4
5


In [65]:
# 행렬 - 인덱스 
# 행렬을 어떻게 인덱스로 만들 것인가?

In [66]:
def func(input_data):
    w = input_data[0, 0]
    x = input_data[0, 1]
    y = input_data[1, 0]
    z = input_data[1, 1]
    

In [67]:
# it = class, 주소값을 내부 포인터. 
# idx = it.multi_index : it라는 객체가 가지고 있는 멤버 변수를 가져온다. (퍼블릭) 튜플 값. 
# c에서는 포인터. 
# 튜플은 readonly 데이터!!!


In [71]:
#x[idx] --> x[(0,0)]
# 튜플로 index값을 준다. 

In [ ]:
# 리턴값이 정수
# x[idx] = 3
# x[idx] = float(tmp_val) + delta_x
# x[idx] = 3이 들어갑니다 .
# x[]

 apt-get install git