## hash 1번

In [1]:
import collections

def solution(participant, completion):
    answer = collections.Counter(participant) - collections.Counter(completion)
    return list(answer.keys())[0]

In [2]:
def solution(participant, completion):
    participant.sort()
    completion.sort()
    for i in range(len(completion)):
        if participant[i] != completion[i]:
            return participant[i]
    return participant[len(participant)-1]

In [3]:
def solution(participant, completion):
    participant.sort()
    completion.sort()
    for p, c in zip(participant, completion):
        if p != c:
            return p
    return participant[-1]

## hash 2번

In [10]:
def solution(phoneBook):
    phoneBook = sorted(phoneBook)

    for p1, p2 in zip(phoneBook, phoneBook[1:]):
        if p2.startswith(p1):
            return False
    return True

In [11]:
def solution(phone_book):
    answer = True
    hash_map = {}
    for phone_number in phone_book:
        hash_map[phone_number] = 1
    for phone_number in phone_book:
        temp = ""
        for number in phone_number:
            temp += number
            if temp in hash_map and temp != phone_number:
                answer = False
    return answer

In [12]:
from collections import Counter
def solution(participant, completion):

    inter = list((Counter(participant) - Counter(completion)).elements())

    return inter.pop()

In [13]:
def solution(participant, completion):
    marathon = {}
    hash_sum = 0
    for p in participant:
        marathon[hash(p)] = p
        hash_sum += hash(p)
    for c in completion:
        hash_sum -= hash(c)
    answer = marathon[hash_sum]
    return answer

## 프로그래머스

In [104]:
def solution(v):
    vsx = [v[0][0], v[1][0], v[2][0]]
    vsy = [v[0][1], v[1][1], v[2][1]]
 
    answer = []

    if vsx[0] != vsx[1] and vsx[0] != vsx[2]:
        answer.append(vsx[0])
    
    elif vsx[0] == vsx[1] and vsx[0] != vsx[2]:
        if vsx[0] == vsx[1]:
            answer.append(vsx[2])
        else:
            answer.append(vsx[1])

    if vsy[0] != vsy[1] and vsy[0] != vsy[2]:
        answer.append(vsy[0])
    
    elif vsy[0] == vsy[1] and vsy[0] != vsy[2]:
        if vsy[0] == vsy[1]:
            answer.append(vsy[2])
        else:
            answer.append(vsy[1])

    print('Hello Python')

    return answer

In [105]:
inp1 = [[1, 4], [3, 4], [3, 10]]
inp2 = [[1, 1], [2, 2], [1, 2]]
test = [1,2,3,4,5]
test[1:]

[2, 3, 4, 5]

In [106]:
solution(inp1)

Hello Python


[1, 10]

In [107]:
def solution(v):
    vsx = [v[0][0], v[1][0], v[2][0]]
    vsy = [v[0][1], v[1][1], v[2][1]]
 
    answer = []
    
    if vsx[0] not in vsx[1:]:
        answer.append(vsx[0])    
        
    elif vsx[2] not in vsx[:1]:
        answer.append(vsx[2])
    
    else:
        answer.append(vsx[1])
        
        
    if vsy[0] not in vsy[1:]:
        answer.append(vsy[0])    
        
    elif vsy[2] not in vsy[:1]:
        answer.append(vsy[2])
    
    else:
        answer.append(vsy[1])

    print('Hello Python')

    return answer

In [108]:
solution(inp1)

Hello Python


[1, 10]

In [109]:
def two_times(numberList):
    result = [ ]
    for number in numberList:
        result.append(number*2)
    return result

result = two_times([1, 2, 3, 4])
print(result)

[2, 4, 6, 8]


## 프로그래머스 2번

In [113]:
def two_times(x): 
    return x*2

In [114]:
list(map(two_times, [1, 2, 3, 4]))

[2, 4, 6, 8]

In [115]:
a, b = map(int, input().strip().split(' '))
print(a + b)

3 5
8


In [126]:
a, b = map(int, input().strip().split(' '))

lista = len(list(range(a)))
star = '*'*lista
star2 = print(star)

for _ in range(1, b):
    print(star)

3 5
***
***
***
***
***


In [90]:
a, b = map(int, input().strip().split(' '))
for i in range(b):
    print('*' * a)

'hi'

In [151]:
def solution(priorities, location):
    target = priorities[location-1]
    
    priorities.sort()
    priorities.reverse()
    
    enumerate(priorities)
    answer = priorities[3][0]
    
    return answer

In [155]:
#solution([2, 1, 3, 2], 2)

priorities = [2, 1, 3, 2]
priorities.sort()
priorities.reverse()
priorities


[3, 2, 2, 1]

In [156]:
priorities.pop(0)

3

In [157]:
priorities

[2, 2, 1]

In [153]:
for i, j in enumerate(priorities):
    if target in priorities:
        

0
1
2
3


In [146]:
print(num)

In [154]:
def solution(priorities, location):
    pi_list = [(p, i) for i, p in enumerate(priorities)]
    waiting_q = []
  
    while pi_list:
        pi = pi_list.pop(0)
        priority = pi[0]
        p_list = [priority for priority, idx in pi_list]
        if p_list:
            max_p = max(p_list)
 
        if priority >= max_p:
            waiting_q.append(pi)
        else:
            pi_list.append(pi)

    for i, item in enumerate(waiting_q):
        if item[1] == location:
            return i + 1

In [138]:
print(a)

In [2]:
one = [30,2] 
riders = [[10,1],[20,2]]

In [4]:
import numpy as np

In [5]:
rider = np.array(riders)

In [6]:
rider

array([[10,  1],
       [20,  2]])

In [ ]:
    
    for i in range(len(riders)-1):
        RidX.append(riders[0][i])
    RidXn = np.array(RidX)
    
    for i in range(len(riders)-1):    
        RidY.append(riders[1][i])
    RidYn = np.array(RidY)

In [7]:
list(range(5))

[0, 1, 2, 3, 4]

In [14]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot()

In [15]:
import numpy as np

def solution(restaurant, riders):
    RidX = []
    RidY = []
    resx = restaurant[0]
    resy = restaurant[1] 
    IndexNumber = []
    answer = []
        
    for i in range(len(riders)-1):
        RidX.append(riders[i][0])
    RidXn = np.array(RidX)
    
    for i in range(len(riders)-1):    
        RidY.append(riders[i][1])
    RidYn = np.array(RidY)
    
    
    for i,j in enumerate(RidX):
        if j > 500:
            IndexNumber.append(i)
    for i,j in enumerate(RidY):
        if j > 500:
            IndexNumber.append(i)
    
    IndexNumbers = set(IndexNumber)
    
    for i in IndexNumbers:
        answer.append(riders[i])
    
    k = len(answer)
    
    return k

In [16]:
restaurant, riders = [0,0], [[-700,0], [150,180], [500,500], [150, -800], [800, 800], [-900, 500], [-1100, 900]]


In [17]:
solution(restaurant, riders)

1

In [27]:
    
    
    RidX = []
    RidY = []
    resx = restaurant[0]
    resy = restaurant[1] 
    IndexNumber = []
    answer = []
        
    for i in range(len(riders)):
        RidX.append(riders[i][0])
    RidXn = np.array(RidX)
    print(RidXn)
    
    for i in range(len(riders)):    
        RidY.append(riders[i][1])
    RidYn = np.array(RidY)
    print(RidYn)
    
    for i,j in enumerate(RidX):
        if j > 500 or j < -500:
            IndexNumber.append(i)
    print(IndexNumber)
    
    for i,j in enumerate(RidY):
        if j > 500 or j < -500:
            IndexNumber.append(i)

    print(IndexNumber)
    
    IndexNumbers = set(IndexNumber)
    print(IndexNumbers)
    
    
    for i in IndexNumbers:
        answer.append(riders[i])
    
    k = len(answer)-1
    print(k)
    

[ -700   150   500   150   800  -900 -1100]
[   0  180  500 -800  800  500  900]
[0, 4, 5, 6]
[0, 4, 5, 6, 3, 4, 6]
{0, 3, 4, 5, 6}
4


In [28]:
len('2019/05/01 00:59:19')

19

In [29]:
import time
import pandas as pd

def solution(logs):
    log = pd.DataFrame(logs, column='logs')
    log[timekr] =  log[logs] - 9
    
    answer = []
    return answer

In [31]:
price = [30, 80, 10]
price = np.array(price, dtype=float)

In [32]:
price/100

array([0.3, 0.8, 0.1])

In [33]:
list(price/100)

[0.3, 0.8, 0.1]

In [ ]:
    p = np.array(prices)
    
    if len(discounts) < len(prices):
        a = len(prices) - len(discounts)
        for i in range(a):
            discounts.append(0)
    
    d = np.array(discounts)

In [ ]:
import numpy as np

def solution(prices, discounts):
    answer = []
    if len(discounts) < len(prices):
        a = len(prices) - len(discounts)
        for i in range(a):
            discounts.append(0)
    discounts = np.array(discounts, dtype=float)
    discounts*0.01
    d = list(discounts)
    
    for i in range(len(prices)):
        ans = prices[i] * d[i]
        answer.append(ans)
    answer = sum(answer)
    
    return answer

In [51]:
13000 - 13000*0.3

88000 - 88000*0.2

70400.0

In [52]:
9100+70400

79500

In [63]:
prices = [13000, 88000, 10000]
discounts = [30, 20]
result = 82000
answer = []


print(prices.sort())

if len(discounts) < len(prices):
    a = len(prices) - len(discounts)
   # print(a)
    for i in range(a):
        discounts.append(0)
    
    discounts.sort()
    discounts.reverse()
    
    discounts = np.array(discounts, dtype=float)
    discounts = abs((discounts*0.01) - 1)
    d = list(discounts)
  #  print(d)

prices.sort()
prices.reverse()

print(prices)
print(d)

for i in range(len(prices)):
    ans = prices[i] * d[i]
    answer.append(ans)

print(answer)
print(sum(answer)*(-1))


None
[88000, 13000, 10000]
[0.7, 0.8, 1.0]
[61599.99999999999, 10400.0, 10000.0]
-82000.0


In [36]:
solution(prices,discounts)

TypeError: solution() takes 1 positional argument but 2 were given

In [58]:
prices = [13000, 88000, 10000]
discounts = [30, 20]
result = 82000
answer = []

prices.sort()
prices.reverse()
print(prices)

[88000, 13000, 10000]


In [ ]:
ls = [3, 1, 2, 7, 4, 9]
ls.sort()
ls.reverse()
print(ls)

In [64]:
def solution(infos, actions):
    answer = []
    infodict = {}
    for i in range(len(infos)):
        infos[i].split(' ')
        infodict[infos[i][0]] = infos[i][1]
    
    if actions[0] != actions[0].startswith('LOGIN'):
        answer.append('false')
        
        
    
    logindict = {}
    for i in range(len(actions)):
        if actions[i] == actions[i].startswith('LOGIN'):
            actions[i].split(' ')
            logindict[actions[i][0]] = logindict[i][1]
            
        
        if logindict[i][0] in infodict.keys():
            logindict[i][0] == infodict['logindict[i][0]']
            answer.append('true')
        else:
            answer.append('false')
            
    
    return answer

In [118]:
infos = ["kim password", "lee abc"]
actions = [
    "ADD 30", 
    "LOGIN kim abc", 
    "LOGIN lee password", 
    "LOGIN kim password", 
    "LOGIN kim password", 
    "ADD 30", 
    "ORDER",
    "ORDER",
    "ADD 40",
    "ADD 50"
]

infodict = {}
for i in range(0, len(infos)):
    info = infos[i].split()
    infodict[info[0]] = info[1]

print(infodict)

{'kim': 'password', 'lee': 'abc'}


In [119]:
logindict ={}
for i in range(0, len(actions)):
    actionlist = actions[i].split()
    if actionlist[0] == 'LOGIN':
        logindict[actionlist[1]]=actionlist[2]
        
logindict
print(logindict)

{'kim': 'password', 'lee': 'password'}


In [125]:
if actions[0] != actions[0].startswith('LOGIN'):
    answer.append('false')

print(answer)

['false', 'false']


In [123]:
while logindict.keys()==infodict.keys():
    if logindict.values()==infodict.values():
        print('true')

KeyboardInterrupt: 

In [132]:
forms =[ ['jm@email.com', '제이엠'], ['jason@email.com', '제이슨'], ['woniee@email.com', '워니'], ['mj@email.com', '엠제이'], ['nowm@email.com', '이제엠'] ]

print(forms[0])
nameform=[]
answer=[]
for i in range(len(forms)):
    nameform.append(forms[i][1])
print(nameform)


['jm@email.com', '제이엠']
['제이엠', '제이슨', '워니', '엠제이', '이제엠']


In [141]:
a = nameform
a.sort()
a.reverse()
print(a)
print(nameform[0][:2], nameform[0][1:])

['제이엠', '제이슨', '이제엠', '워니', '엠제이']
제이 이엠


In [154]:
snameform=[]
for i in range(len(nameform)):
    snameform.append(nameform[i][:2])
print(snameform)

enameform=[]
for i in range(len(nameform)):
    enameform.append(nameform[i][1:])
print(enameform)

answer =[]
if snameform[0] in snameform[1:]:
    answer.append(nameform[0])
    answer.index
print(answer)

['제이', '제이', '이제', '워니', '엠제']
['이엠', '이슨', '제엠', '니', '제이']
['제이엠']


In [183]:
user = "mrko"
friends = [["donut", "andole"], 
           ["donut", "jun"], ["donut", "mrko"], 
           ["shakevan", "andole"], ["shakevan", "jun"], 
           ["shakevan", "mrko"]]
visitors= ["bedi", "bedi", "donut", "bedi", "shakevan"]
result = ['andole', 'jun','bedi']

In [184]:
visitor=list(set(visitors))
visitor

['bedi', 'shakevan', 'donut']

In [215]:
answer=[]
for i in range(len(visitor)):
    for j in range(len(friends)):
        if visitor[i] in friends[j][0] or visitor[i] in friends[j][1]:
            answer.append(friends[j][1]) 
        elif (visitor[i] not in friends[j][0]) and (visitor[i] not in friends[j][1]): 
            answer.append(visitor[i])


answer = list(set(answer))
fri=['donut','shakevan']

if user in answer:
    answer.remove(user)

answer.remove(fri[0])
answer.remove(fri[1])

1- donut
2- andole
1- donut
2- jun
1- donut
2- mrko
1- shakevan
2- andole
1- shakevan
2- jun
1- shakevan
2- mrko


In [216]:
answer

['jun', 'bedi', 'andole']

In [231]:
def solution(infos, actions):
    answer = []
    infodict = {}
    infolist = []
    for i in range(0, len(infos)):
        info = infos[i].split()
        infolist.append(info)
        
    logindict ={}
    loginlist=[]
    for i in range(0, len(actions)):
        actionlist = actions[i].split()
        if actionlist[0] == 'LOGIN':
            logindict[actionlist[1]]=actionlist[2]
            loginlist.append(actionlist)
    
        for i in range(len(loginlist)):
            if loginlist[i][0] == 'LOGIN':
                if (infolist[0][0] == loginlist[i][1]) and (infolist[0][1] == loginlist[i][2]):
                    answer.append('true')
                elif (infolist[1][0] != loginlist[i][1]) and (infolist[1][1] == loginlist[i][2]):
                    answer.append('false')
    
    print(loginlist)
    print(infolist)
    
    return answer

In [232]:
solution(infos, actions)

[['LOGIN', 'kim', 'abc'], ['LOGIN', 'lee', 'password'], ['LOGIN', 'kim', 'password'], ['LOGIN', 'kim', 'password']]
[['kim', 'password'], ['lee', 'abc']]


['false',
 'false',
 'false',
 'true',
 'false',
 'true',
 'true',
 'false',
 'true',
 'true',
 'false',
 'true',
 'true',
 'false',
 'true',
 'true',
 'false',
 'true',
 'true',
 'false',
 'true',
 'true']